import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";

import NavBar from "./components/navbar";
import Footer from "./components/footer";

// const inter = Inter({ subsets: ["latin"] });
const archivo = Archivo({subsets: ["latin"], weight:["100", "200", "300", "400", "500", "600", "700", "800", "900"]})

export const metadata: Metadata = {
  title: "Hng Stage 2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={archivo.className}>
      <NavBar />
      {children}
      <Footer />
      </body>
    </html>
  );
}
